version: '3.2'

services:
  db:
    restart: unless-stopped
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: "nodle"
      POSTGRES_DB: "nodle"
      POSTGRES_PASSWORD: "password"
    volumes:
     - nodle_db:/var/lib/postgresql/data
    ports:
     - "127.0.0.1:54321:5432"

  indexer:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file:
      - .env
    command: ["sh", "-c", "npm i && npm run start"]


volumes:
  nodle_db:
