{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.frontend.service.annotations }}
  annotations:
{{ toYaml .Values.frontend.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "nodle.frontend.labels" . | nindent 4 }}
{{- if .Values.frontend.service.labels }}
{{ toYaml .Values.frontend.service.labels | indent 4 }}
{{- end }}
  name: {{ template "nodle.frontend.fullname" . }}
{{ include "nodle.namespace" . | indent 2 }}
spec:
{{- if .Values.frontend.service.clusterIP }}
  clusterIP: {{ .Values.frontend.service.clusterIP }}
{{- end }}
{{- if .Values.frontend.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.frontend.service.externalIPs | indent 4 }}
{{- end }}
{{- if .Values.frontend.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.frontend.service.loadBalancerIP }}
{{- end }}
{{- if .Values.frontend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range $cidr := .Values.frontend.service.loadBalancerSourceRanges }}
    - {{ $cidr }}
  {{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.servicePort }}
      protocol: TCP
      targetPort: 80
    {{- if .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
    {{- end }}
  selector:
    {{- include "nodle.frontend.matchLabels" . | nindent 4 }}
{{- if .Values.frontend.service.sessionAffinity }}
  sessionAffinity: {{ .Values.frontend.service.sessionAffinity }}
{{- end }}
  type: "{{ .Values.frontend.service.type }}"
{{- end }}
