{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodle.frontend.fullname" . }}
  labels:
    {{- include "nodle.frontend.labels" . | nindent 4 }}
{{ include "nodle.namespace" . | indent 2 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "nodle.frontend.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "nodle.frontend.labels" . | nindent 8 }}
      {{- if .Values.frontend.podLabels}}
      {{ toYaml .Values.frontend.podLabels | nindent 8 }}
      {{- end}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "nodle.name" . }}-{{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          resources:
{{ toYaml .Values.frontend.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
