{{- if .Values.graphql.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodle.graphql.fullname" . }}
  labels:
    {{- include "nodle.graphql.labels" . | nindent 4 }}
{{ include "nodle.namespace" . | indent 2 }}
spec:
  replicas: {{ .Values.graphql.replicaCount }}
  selector:
    matchLabels:
      {{- include "nodle.graphql.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- include "nodle.graphql.labels" . | nindent 8 }}
      {{- if .Values.graphql.podLabels}}
      {{ toYaml .Values.graphql.podLabels | nindent 8 }}
      {{- end}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "nodle.name" . }}-{{ .Values.graphql.name }}
          image: "{{ .Values.graphql.image.repository }}:{{ .Values.graphql.image.tag }}"
          imagePullPolicy: {{ .Values.graphql.image.pullPolicy }}
          command:
            - npm
            - run
            - start:server
          env:
            # database
            - name: TYPEORM_HOST
              valueFrom:
                secretKeyRef:
                  key: database_host
                  name: {{ template "nodle.indexer.fullname" . }}
            - name: TYPEORM_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database_name
                  name: {{ template "nodle.indexer.fullname" . }}
            - name: TYPEORM_USERNAME
              valueFrom:
                secretKeyRef:
                  key: database_username
                  name: {{ template "nodle.indexer.fullname" . }}
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database_password
                  name: {{ template "nodle.indexer.fullname" . }}
            - name: TYPEORM_PORT
              valueFrom:
                secretKeyRef:
                  key: database_port
                  name: {{ template "nodle.indexer.fullname" . }}
            - name: RABBIT_MQ_URL
              valueFrom:
                secretKeyRef:
                  key: rabbitmq_url
                  name: {{ template "nodle.indexer.fullname" . }}
            - name: WS_PROVIDER
              valueFrom:
                secretKeyRef:
                  key: chain_node
                  name: {{ template "nodle.indexer.fullname" . }}
          readinessProbe:
            httpGet:
              path: /
              port: 4000
              httpHeaders:
                - name: Accept
                  value: text/html
          resources:
{{ toYaml .Values.graphql.resources | indent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
