apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "nodle.indexer.labels" . | nindent 4 }}
  name: {{ template "nodle.indexer.fullname" . }}
{{ include "nodle.namespace" . | indent 2 }}
data:
  database_host: {{ .Values.secrets.databaseHost | b64enc }}
  database_name: {{ .Values.secrets.databaseName | b64enc }}
  database_username: {{ .Values.secrets.databaseUser | b64enc }}
  database_password: {{ .Values.secrets.databasePassword | b64enc }}
  database_port: {{ .Values.secrets.databasePort | b64enc }}
  rabbitmq_host: {{ .Values.secrets.rabbitMQHost | b64enc }}
  rabbitmq_port: {{ .Values.secrets.rabbitMQPort | b64enc }}
  rabbitmq_user: {{ .Values.secrets.rabbitMQUser | b64enc }}
  rabbitmq_passwor: {{ .Values.secrets.rabbitMQPassword | b64enc }}
