apiVersion: v1
kind: Service
metadata:
  name: {{ include "node.websocketService" . }}
  labels:
    {{- include "node.labels" . | nindent 4 }}
spec:
  ports:
    - port: 9944
      name: websocket-rpc
  selector:
    {{- include "node.selectorLabels" . | nindent 4 }}