name: Docker build

on:
  push:
    branches:
      - master
      - NOD-216-prod-mode

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run prettier-check
      - run: npm run lint
      - run: npm run build
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker build dev
        run: make docker-build-dev
      - name: Run docker build prod
        run: make docker-build-prod
  publish:
    if: ${{ github.repository_owner == 'NodleCode' }}
    name: Publish docker image to Google Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: vars
        run: echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
      - uses: actions/checkout@v2
      - name: Run docker build prod
        run: make docker-build-prod
      - run: docker tag nodle:prod gcr.io/${{ secrets.GCP_PROJECT_ID_TEST }}/app:${{steps.vars.outputs.sha}}
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_TEST }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS_TEST }}
          export_default_credentials: true
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID_TEST }}/app:${{steps.vars.outputs.sha}}
